# Site settings
title: Kettul
email: hello@kettul.com
description: > # this means to ignore newlines until "baseurl:"
  Kettul is a nimble development team that specializes
  in crafting Drupal and Ruby on Rails applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kettul.com" # the base hostname & protocol for your site
twitter_username: kettuldev

# Build settings
markdown: kramdown
exclude: ['README.md','*.json','Gemfile','Gemfile.lock','Guardfile','*.json','public', vendor]

nav:
 - ["Services", "/#services"]
 - ["Our Team", "/#team"]
 - ["Clients", "/#clients"]
 - ["Contact", "/#contact"]

 gems:
  - jekyll-assets

assets:
  compress:
    css: false | true | default - development: false, production: true
    js: false | true | default - development: false, production: true
  autowrite: true
  cache: false | directory | default: .asset-cache
  cache_type: memory | filesystem | default: filesystem
  cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "bundle.css"
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
  features:
    liquid: true | false | default: false
    integrity: true | false | default: false
    # This will add height and width attributes for an img tag.
    automatic_img_size: true | false | n(fixnum): 2,4,6,8 | default: true
    # This will add the digest path as an alt attribute for an img tag.
    automatic_img_alt : true | false | default: true