# Site settings
title: Kettul
email: hello@kettul.com
description: > # this means to ignore newlines until "baseurl:"
  Kettul is a nimble development team that specializes
  in crafting Drupal and Ruby on Rails applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kettul.com" # the base hostname & protocol for your site
twitter_username: kettuldev

# Build settings
markdown: kramdown
exclude: ['README.md','*.json','Gemfile','Gemfile.lock','Guardfile','*.json','public', vendor]

nav:
 - ["What we do", "/#services"]
 - ["Case study", "/#case-study"]
 - ["Our team", "/#team"]
 - ["Clients", "/#clients"]
 - ["Contact", "javascript:void(0);"]